/**
 * MONOLITH Digital Shadow Service — Event Bus Types
 * Redis Streams event definitions
 */

// ─── Event Bus Configuration ─────────────────────────────────────────────────

export interface EventBusConfig {
  /** Redis stream key prefix */
  streamPrefix: string;
  /** Consumer group name */
  consumerGroup: string;
  /** Consumer name (unique per instance) */
  consumerName: string;
  /** Max stream length (trimming) */
  maxStreamLength: number;
  /** Block timeout for XREAD (ms) */
  blockTimeoutMs: number;
}

// ─── Event Envelope ──────────────────────────────────────────────────────────

export interface EventEnvelope<T = unknown> {
  /** Unique event ID (generated by Redis) */
  id: string;
  /** Event stream/channel name */
  stream: EventStream;
  /** Event type discriminator */
  type: string;
  /** Source service */
  source: string;
  /** Event timestamp */
  timestamp: Date;
  /** Correlation ID for tracing */
  correlationId?: string;
  /** Event payload */
  data: T;
}

/** Available event streams in Digital Shadow */
export enum EventStream {
  /** Machine state transitions */
  MACHINE_STATE = 'ds:machine:state',
  /** Sensor telemetry batches */
  SENSOR_TELEMETRY = 'ds:sensor:telemetry',
  /** Machine alarms */
  MACHINE_ALARM = 'ds:machine:alarm',
  /** Job lifecycle events */
  JOB_LIFECYCLE = 'ds:job:lifecycle',
  /** System health/heartbeat */
  SYSTEM_HEALTH = 'ds:system:health',
  /** CAS write confirmations */
  CAS_WRITE = 'ds:cas:write',
  /** Safety gate results */
  SAFETY_GATE = 'ds:safety:gate',
}

// ─── Event Handlers ──────────────────────────────────────────────────────────

export type EventHandler<T = unknown> = (event: EventEnvelope<T>) => Promise<void>;

export interface EventSubscription {
  stream: EventStream;
  handler: EventHandler;
  /** Filter by event type (optional) */
  eventTypeFilter?: string[];
}

// ─── Health Check Types ──────────────────────────────────────────────────────

export interface ServiceHealth {
  service: string;
  status: 'healthy' | 'degraded' | 'unhealthy';
  lastCheck: Date;
  details: Record<string, unknown>;
  uptime: number;
  connections: ConnectionHealth[];
}

export interface ConnectionHealth {
  name: string;
  type: 'opcua' | 'mqtt' | 'influxdb' | 'redis' | 'http';
  status: 'connected' | 'disconnected' | 'reconnecting';
  lastActivity: Date;
  errorCount: number;
}
