/**
 * Zip Bundle - Deterministic zip creation for exports
 * P2.2 Export UX (Gated)
 *
 * Uses browser-safe Web Crypto API (no Node.js crypto)
 *
 * @version 0.12.1
 */

import { sha256Hex } from "../../../crypto/sha256";

// ============================================================================
// Types
// ============================================================================

export interface BundleFile {
  /** Path within the zip (e.g., "sheet_01.nc") */
  path: string;
  /** File content */
  content: string | Uint8Array;
  /** Optional comment */
  comment?: string;
}

export interface BundleOptions {
  /** Job ID for naming */
  jobId: string;
  /** Files to include */
  files: BundleFile[];
  /** Optional metadata to include */
  metadata?: Record<string, unknown>;
}

export interface BundleResult {
  /** The bundle content (string for browser compatibility) */
  data: string | Uint8Array;
  /** SHA-256 hash of the bundle */
  sha256: string;
  /** Size in bytes */
  sizeBytes: number;
  /** Filename */
  filename: string;
  /** File manifest */
  manifest: {
    path: string;
    sha256: string;
    sizeBytes: number;
  }[];
}

// ============================================================================
// Deterministic Zip Creation (Mock Implementation)
// ============================================================================

/**
 * Create a deterministic bundle.
 *
 * Note: This is a simplified implementation for MVP.
 * In production, use a proper zip library with deterministic settings.
 */
export async function createBundle(options: BundleOptions): Promise<BundleResult> {
  const { jobId, files, metadata } = options;

  // Sort files for determinism
  const sortedFiles = [...files].sort((a, b) => a.path.localeCompare(b.path));

  // Create manifest
  const manifest: BundleResult["manifest"] = [];
  const fileContents: string[] = [];

  for (const file of sortedFiles) {
    const content = typeof file.content === "string"
      ? file.content
      : new TextDecoder().decode(file.content);

    const fileHash = await sha256Hex(content);
    const sizeBytes = new TextEncoder().encode(content).length;

    manifest.push({
      path: file.path,
      sha256: fileHash,
      sizeBytes,
    });

    fileContents.push(`--- ${file.path} ---\n${content}`);
  }

  // Add export metadata
  const exportMeta = {
    jobId,
    exportedAt: new Date(0).toISOString(), // Fixed timestamp for determinism
    files: manifest,
    ...(metadata || {}),
  };

  const metaContent = JSON.stringify(exportMeta, null, 2);
  fileContents.push(`--- export.meta.json ---\n${metaContent}`);

  // Create "bundle" (simplified - in production use real zip)
  const bundleContent = fileContents.join("\n\n");
  const bundleBytes = new TextEncoder().encode(bundleContent);
  const bundleSha256 = await sha256Hex(bundleBytes);

  const filename = `${jobId}_export.zip`;

  return {
    data: bundleContent, // Return string instead of Buffer for browser
    sha256: bundleSha256,
    sizeBytes: bundleBytes.length,
    filename,
    manifest,
  };
}

/**
 * Create a mock G-code bundle for testing.
 */
export async function createMockGcodeBundle(
  jobId: string,
  dialect: string,
  sheetCount: number
): Promise<BundleResult> {
  const files: BundleFile[] = [];

  // Add G-code files for each sheet
  for (let i = 1; i <= sheetCount; i++) {
    const sheetId = String(i).padStart(2, "0");
    files.push({
      path: `sheet_${sheetId}.nc`,
      content: generateMockGcode(jobId, sheetId, dialect),
    });
  }

  // Add manifest
  files.push({
    path: "manifest.json",
    content: JSON.stringify({
      version: "1.0.0",
      jobId,
      dialect,
      sheetCount,
      generatedAt: new Date(0).toISOString(),
      toolVersion: "IIMOS Export 0.12.1",
    }, null, 2),
  });

  return createBundle({
    jobId,
    files,
    metadata: {
      dialect,
      sheetCount,
      generatedBy: "IIMOS Export Service",
    },
  });
}

/**
 * Generate mock G-code content.
 */
function generateMockGcode(jobId: string, sheetId: string, dialect: string): string {
  const header = getDialectHeader(dialect);

  return `${header}
; Job: ${jobId}
; Sheet: ${sheetId}
; Dialect: ${dialect}
; Generated by IIMOS Export Service
;
G21 ; Metric units
G90 ; Absolute positioning
G17 ; XY plane selection
;
; Tool setup
T1 M6 ; Select tool 1
S18000 M3 ; Spindle on at 18000 RPM
;
; Rapid to start position
G0 X0 Y0 Z50
G0 Z5
;
; Begin cutting
G1 Z-5 F1000
G1 X100 Y0 F3000
G1 X100 Y100
G1 X0 Y100
G1 X0 Y0
;
; Retract
G0 Z50
;
; End program
M5 ; Spindle off
M30 ; Program end
%
`;
}

/**
 * Get dialect-specific G-code header.
 */
function getDialectHeader(dialect: string): string {
  switch (dialect) {
    case "KDT":
      return `; KDT CNC G-code
; ISO 6983-1 compatible
%`;
    case "BIESSE":
      return `; Biesse CNC G-code
; ISO standard with Biesse extensions
%`;
    case "HOMAG":
      return `; Homag CNC G-code
; ISO standard with Homag extensions
%`;
    default:
      return `; Generic G-code
%`;
  }
}

// ============================================================================
// Hash Utilities
// ============================================================================

/**
 * Calculate SHA-256 hash of content (async, browser-safe).
 */
export async function calculateSha256(content: string | Uint8Array): Promise<string> {
  return sha256Hex(content);
}

/**
 * Truncate hash for display.
 */
export function truncateHash(hash: string, length = 16): string {
  if (hash.length <= length * 2 + 3) return hash;
  return `${hash.slice(0, length)}...${hash.slice(-8)}`;
}
