-- ─── Migration: 20270210_qc_anomaly_detection ────────────────────────────────
-- QC Anomaly Detection module for MONOLITH v18.0
-- Tables  : qca_threshold_configs, qca_measurements, qca_anomaly_events
-- View    : qca_anomaly_summary_v
-- Functions: qca_is_enterprise, qca_set_updated_at, qca_detect_anomaly
-- RLS     : ENTERPRISE plan gate; INSERT/UPDATE/DELETE = ADMIN+ (hierarchy_level ≥ 80)
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── Enums ───────────────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE qca_threshold_type AS ENUM ('MIN', 'MAX', 'RANGE', 'ZSCORE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE qca_metric_key AS ENUM (
    'DEFECT_RATE',
    'CYCLE_TIME',
    'YIELD_RATE',
    'SCRAP_RATE',
    'REWORK_RATE',
    'DOWNTIME',
    'CUSTOM'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE qca_anomaly_severity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE qca_anomaly_status AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ─── Helper: plan gate ───────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION qca_is_enterprise(p_org_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.organizations
    WHERE org_id = p_org_id
      AND plan   = 'ENTERPRISE'
  );
$$;

-- ─── Helper: updated_at trigger ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION qca_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- ─── Tables ──────────────────────────────────────────────────────────────────

-- Threshold configurations per org + metric
CREATE TABLE IF NOT EXISTS qca_threshold_configs (
  id               uuid                  PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id           uuid                  NOT NULL REFERENCES public.organizations(org_id) ON DELETE CASCADE,
  metric_key       qca_metric_key        NOT NULL,
  threshold_type   qca_threshold_type    NOT NULL,
  min_value        numeric(18, 6),
  max_value        numeric(18, 6),
  zscore_threshold numeric(6, 3)         DEFAULT 3.0,
  is_active        boolean               NOT NULL DEFAULT TRUE,
  description      text,
  created_by       uuid                  NOT NULL REFERENCES auth.users(id),
  created_at       timestamptz           NOT NULL DEFAULT now(),
  updated_at       timestamptz           NOT NULL DEFAULT now(),

  CONSTRAINT qca_threshold_configs_min_max_check
    CHECK (min_value IS NULL OR max_value IS NULL OR min_value <= max_value),
  CONSTRAINT qca_threshold_configs_zscore_pos
    CHECK (zscore_threshold IS NULL OR zscore_threshold > 0)
);

DROP TRIGGER IF EXISTS qca_threshold_configs_updated_at ON qca_threshold_configs;
CREATE TRIGGER qca_threshold_configs_updated_at
  BEFORE UPDATE ON qca_threshold_configs
  FOR EACH ROW EXECUTE FUNCTION qca_set_updated_at();

-- Raw measurement submissions
CREATE TABLE IF NOT EXISTS qca_measurements (
  id           uuid              PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id       uuid              NOT NULL REFERENCES public.organizations(org_id) ON DELETE CASCADE,
  metric_key   qca_metric_key    NOT NULL,
  value        numeric(18, 6)    NOT NULL,
  measured_at  timestamptz       NOT NULL DEFAULT now(),
  source       text,
  notes        text,
  created_by   uuid              NOT NULL REFERENCES auth.users(id),
  created_at   timestamptz       NOT NULL DEFAULT now()
);

-- Anomaly events auto-generated by trigger on measurement insert
CREATE TABLE IF NOT EXISTS qca_anomaly_events (
  id                      uuid                  PRIMARY KEY DEFAULT gen_random_uuid(),
  org_id                  uuid                  NOT NULL REFERENCES public.organizations(org_id) ON DELETE CASCADE,
  metric_key              qca_metric_key        NOT NULL,
  measurement_id          uuid                  NOT NULL REFERENCES qca_measurements(id) ON DELETE CASCADE,
  threshold_id            uuid                  NOT NULL REFERENCES qca_threshold_configs(id) ON DELETE CASCADE,
  severity                qca_anomaly_severity  NOT NULL,
  status                  qca_anomaly_status    NOT NULL DEFAULT 'OPEN',
  measured_value          numeric(18, 6)        NOT NULL,
  threshold_breach_detail jsonb                 NOT NULL DEFAULT '{}',
  acknowledged_by         uuid                  REFERENCES auth.users(id),
  acknowledged_at         timestamptz,
  resolved_by             uuid                  REFERENCES auth.users(id),
  resolved_at             timestamptz,
  notes                   text,
  created_at              timestamptz           NOT NULL DEFAULT now(),
  updated_at              timestamptz           NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS qca_anomaly_events_updated_at ON qca_anomaly_events;
CREATE TRIGGER qca_anomaly_events_updated_at
  BEFORE UPDATE ON qca_anomaly_events
  FOR EACH ROW EXECUTE FUNCTION qca_set_updated_at();

-- ─── Auto-detection trigger ──────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION qca_detect_anomaly()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_threshold    qca_threshold_configs%ROWTYPE;
  v_severity     qca_anomaly_severity;
  v_breach       jsonb;
  v_is_anomaly   boolean;
  v_mean         numeric;
  v_stddev       numeric;
  v_zscore       numeric;
BEGIN
  FOR v_threshold IN
    SELECT *
    FROM   qca_threshold_configs
    WHERE  org_id     = NEW.org_id
      AND  metric_key = NEW.metric_key
      AND  is_active  = TRUE
  LOOP
    v_is_anomaly := FALSE;
    v_breach     := '{}'::jsonb;
    v_zscore     := NULL;

    CASE v_threshold.threshold_type

      WHEN 'MIN' THEN
        IF NEW.value < v_threshold.min_value THEN
          v_is_anomaly := TRUE;
          v_breach := jsonb_build_object(
            'type',            'MIN',
            'min_value',       v_threshold.min_value,
            'measured_value',  NEW.value
          );
        END IF;

      WHEN 'MAX' THEN
        IF NEW.value > v_threshold.max_value THEN
          v_is_anomaly := TRUE;
          v_breach := jsonb_build_object(
            'type',            'MAX',
            'max_value',       v_threshold.max_value,
            'measured_value',  NEW.value
          );
        END IF;

      WHEN 'RANGE' THEN
        IF NEW.value < v_threshold.min_value OR NEW.value > v_threshold.max_value THEN
          v_is_anomaly := TRUE;
          v_breach := jsonb_build_object(
            'type',            'RANGE',
            'min_value',       v_threshold.min_value,
            'max_value',       v_threshold.max_value,
            'measured_value',  NEW.value
          );
        END IF;

      WHEN 'ZSCORE' THEN
        SELECT AVG(m.value), STDDEV_POP(m.value)
        INTO   v_mean, v_stddev
        FROM (
          SELECT value
          FROM   qca_measurements
          WHERE  org_id     = NEW.org_id
            AND  metric_key = NEW.metric_key
            AND  id        != NEW.id
          ORDER BY measured_at DESC
          LIMIT 30
        ) m;

        IF v_stddev IS NOT NULL AND v_stddev > 0 THEN
          v_zscore := ABS((NEW.value - v_mean) / v_stddev);
          IF v_zscore > COALESCE(v_threshold.zscore_threshold, 3.0) THEN
            v_is_anomaly := TRUE;
            v_breach := jsonb_build_object(
              'type',            'ZSCORE',
              'zscore',          v_zscore,
              'mean',            v_mean,
              'stddev',          v_stddev,
              'threshold',       COALESCE(v_threshold.zscore_threshold, 3.0),
              'measured_value',  NEW.value
            );
          END IF;
        END IF;

    END CASE;

    IF v_is_anomaly THEN
      -- Derive severity
      IF v_threshold.threshold_type = 'ZSCORE' AND v_zscore IS NOT NULL THEN
        IF    v_zscore >= 5.0 THEN v_severity := 'CRITICAL';
        ELSIF v_zscore >= 4.0 THEN v_severity := 'HIGH';
        ELSIF v_zscore >= 3.5 THEN v_severity := 'MEDIUM';
        ELSE                       v_severity := 'LOW';
        END IF;
      ELSE
        -- For MIN/MAX/RANGE: derive from % breach relative to threshold span
        DECLARE
          v_span    numeric;
          v_pct_err numeric;
        BEGIN
          v_span := COALESCE(v_threshold.max_value, v_threshold.min_value);
          IF v_span IS NOT NULL AND v_span <> 0 THEN
            v_pct_err := ABS(NEW.value - v_span) / ABS(v_span);
            IF    v_pct_err >= 0.50 THEN v_severity := 'CRITICAL';
            ELSIF v_pct_err >= 0.20 THEN v_severity := 'HIGH';
            ELSIF v_pct_err >= 0.05 THEN v_severity := 'MEDIUM';
            ELSE                         v_severity := 'LOW';
            END IF;
          ELSE
            v_severity := 'MEDIUM';
          END IF;
        END;
      END IF;

      INSERT INTO qca_anomaly_events (
        org_id, metric_key, measurement_id, threshold_id,
        severity, status, measured_value, threshold_breach_detail
      ) VALUES (
        NEW.org_id, NEW.metric_key, NEW.id, v_threshold.id,
        v_severity, 'OPEN', NEW.value, v_breach
      );
    END IF;

  END LOOP;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS qca_measurements_detect_anomaly ON qca_measurements;
CREATE TRIGGER qca_measurements_detect_anomaly
  AFTER INSERT ON qca_measurements
  FOR EACH ROW EXECUTE FUNCTION qca_detect_anomaly();

-- ─── View: anomaly summary per org + metric ──────────────────────────────────

CREATE OR REPLACE VIEW qca_anomaly_summary_v AS
SELECT
  org_id,
  metric_key,
  COUNT(*)        FILTER (WHERE status = 'OPEN')         AS open_count,
  COUNT(*)        FILTER (WHERE status = 'ACKNOWLEDGED') AS acknowledged_count,
  COUNT(*)        FILTER (WHERE status = 'RESOLVED')     AS resolved_count,
  MAX(created_at) FILTER (WHERE status = 'OPEN')         AS last_open_anomaly_at,
  MAX(created_at)                                        AS last_anomaly_at
FROM  qca_anomaly_events
GROUP BY org_id, metric_key;

-- ─── Row-Level Security ───────────────────────────────────────────────────────

ALTER TABLE qca_threshold_configs   ENABLE ROW LEVEL SECURITY;
ALTER TABLE qca_measurements        ENABLE ROW LEVEL SECURITY;
ALTER TABLE qca_anomaly_events      ENABLE ROW LEVEL SECURITY;

-- qca_threshold_configs -------------------------------------------------------

DROP POLICY IF EXISTS qca_threshold_configs_select ON qca_threshold_configs;
CREATE POLICY qca_threshold_configs_select ON qca_threshold_configs
  FOR SELECT USING (
    qca_is_enterprise(org_id)
    AND auth.uid() IN (
      SELECT user_id FROM org_members WHERE org_id = qca_threshold_configs.org_id
    )
  );

DROP POLICY IF EXISTS qca_threshold_configs_insert ON qca_threshold_configs;
CREATE POLICY qca_threshold_configs_insert ON qca_threshold_configs
  FOR INSERT WITH CHECK (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_threshold_configs.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

DROP POLICY IF EXISTS qca_threshold_configs_update ON qca_threshold_configs;
CREATE POLICY qca_threshold_configs_update ON qca_threshold_configs
  FOR UPDATE USING (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_threshold_configs.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

DROP POLICY IF EXISTS qca_threshold_configs_delete ON qca_threshold_configs;
CREATE POLICY qca_threshold_configs_delete ON qca_threshold_configs
  FOR DELETE USING (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_threshold_configs.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

-- qca_measurements ------------------------------------------------------------

DROP POLICY IF EXISTS qca_measurements_select ON qca_measurements;
CREATE POLICY qca_measurements_select ON qca_measurements
  FOR SELECT USING (
    qca_is_enterprise(org_id)
    AND auth.uid() IN (
      SELECT user_id FROM org_members WHERE org_id = qca_measurements.org_id
    )
  );

DROP POLICY IF EXISTS qca_measurements_insert ON qca_measurements;
CREATE POLICY qca_measurements_insert ON qca_measurements
  FOR INSERT WITH CHECK (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_measurements.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

DROP POLICY IF EXISTS qca_measurements_delete ON qca_measurements;
CREATE POLICY qca_measurements_delete ON qca_measurements
  FOR DELETE USING (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_measurements.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

-- qca_anomaly_events ----------------------------------------------------------

DROP POLICY IF EXISTS qca_anomaly_events_select ON qca_anomaly_events;
CREATE POLICY qca_anomaly_events_select ON qca_anomaly_events
  FOR SELECT USING (
    qca_is_enterprise(org_id)
    AND auth.uid() IN (
      SELECT user_id FROM org_members WHERE org_id = qca_anomaly_events.org_id
    )
  );

DROP POLICY IF EXISTS qca_anomaly_events_update ON qca_anomaly_events;
CREATE POLICY qca_anomaly_events_update ON qca_anomaly_events
  FOR UPDATE USING (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_anomaly_events.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

DROP POLICY IF EXISTS qca_anomaly_events_delete ON qca_anomaly_events;
CREATE POLICY qca_anomaly_events_delete ON qca_anomaly_events
  FOR DELETE USING (
    qca_is_enterprise(org_id)
    AND EXISTS (
      SELECT 1 FROM org_members
      WHERE org_id          = qca_anomaly_events.org_id
        AND user_id         = auth.uid()
        AND is_active = TRUE
        AND role IN ('managing_director', 'governance')
    )
  );

-- ─── Indexes ─────────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS qca_threshold_configs_org_metric
  ON qca_threshold_configs (org_id, metric_key);

CREATE INDEX IF NOT EXISTS qca_threshold_configs_org_active
  ON qca_threshold_configs (org_id, is_active);

CREATE INDEX IF NOT EXISTS qca_measurements_org_metric_at
  ON qca_measurements (org_id, metric_key, measured_at DESC);

CREATE INDEX IF NOT EXISTS qca_anomaly_events_org_status
  ON qca_anomaly_events (org_id, status);

CREATE INDEX IF NOT EXISTS qca_anomaly_events_org_metric
  ON qca_anomaly_events (org_id, metric_key);

CREATE INDEX IF NOT EXISTS qca_anomaly_events_measurement_id
  ON qca_anomaly_events (measurement_id);

CREATE INDEX IF NOT EXISTS qca_anomaly_events_threshold_id
  ON qca_anomaly_events (threshold_id);

-- ─── Assertion Block ─────────────────────────────────────────────────────────

DO $$
DECLARE
  tbl_count  int;
  view_count int;
BEGIN
  SELECT COUNT(*) INTO tbl_count
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_name IN (
      'qca_threshold_configs',
      'qca_measurements',
      'qca_anomaly_events'
    );

  SELECT COUNT(*) INTO view_count
  FROM information_schema.views
  WHERE table_schema = 'public'
    AND table_name = 'qca_anomaly_summary_v';

  ASSERT tbl_count  = 3, 'Expected 3 qca_ tables; found: '  || tbl_count;
  ASSERT view_count = 1, 'Expected qca_anomaly_summary_v view; found: ' || view_count;

  RAISE NOTICE '20270210_qc_anomaly_detection: % tables + % view verified OK', tbl_count, view_count;
END $$;
