/**
 * cix.ts - Biesse CIX Format Post Processor
 *
 * Generates Biesse-compatible CIX (XML) files for Biesse CNC machining centers.
 * CIX is an XML-based format used by bSolid/bNest software to program Biesse
 * Rover, Skipper, and other woodworking CNC machines.
 *
 * ## CIX Format Overview
 *
 * ```xml
 * <?xml version="1.0" encoding="UTF-8"?>
 * <PROGRAM name="panel_001">
 *   <HEADER>
 *     <DIM X="600" Y="720" Z="18"/>
 *   </HEADER>
 *   <MACHINING>
 *     <BORE X="50" Y="37" Z="-12.5" DIA="8" THROUGH="no" TNO="1"/>
 *   </MACHINING>
 * </PROGRAM>
 * ```
 *
 * ## Supported Operations
 * - BORE: Vertical/horizontal drilling (DRILL + BORE operation types)
 * - Unsupported types emit warnings (POCKET, PROFILE, SLOT reserved for future)
 *
 * @see https://forums.autodesk.com/t5/hsm-post-processor-ideas/biesse-woodworking-router-using-cix-format/idi-p/7470469
 * @version 1.0.0 - Phase T028-P3: CIX post-processor
 */

import type { MachineProfile } from '../../machine/machineProfile';
import type {
  OperationGraph,
  Operation,
  DrillOperation,
  BoreOperation,
} from '../../operation/operationTypes';
import type {
  PostProcessor,
  PostProcessOptions,
  PostProcessResult,
  PostProcessStats,
  ToolMap,
} from '../types';
import { normalizeOperations } from '../normalizeOperations';
import { formatTimestamp } from '../emit/format';
import { getNfpHeaderLines } from '../nfpHeader';

// ============================================================================
// Constants
// ============================================================================

const DEFAULT_THICKNESS = 18;
const XML_DECLARATION = '<?xml version="1.0" encoding="UTF-8"?>';
const INDENT = '  ';

// ============================================================================
// CIX Post Processor
// ============================================================================

export const cixPostProcessor: PostProcessor = {
  dialect: 'CIX',
  fileExt: '.cix',

  post(
    opGraph: OperationGraph,
    machine: MachineProfile,
    opts: PostProcessOptions
  ): PostProcessResult {
    try {
      return generateCix(opGraph, machine, opts);
    } catch (error) {
      return {
        status: 'FAIL',
        errors: [
          `CIX post-processor error: ${error instanceof Error ? error.message : String(error)}`,
        ],
      };
    }
  },
};

// ============================================================================
// Main Generation Function
// ============================================================================

function generateCix(
  opGraph: OperationGraph,
  machine: MachineProfile,
  opts: PostProcessOptions
): PostProcessResult {
  const warnings: string[] = [];
  const lines: string[] = [];

  lines.push(XML_DECLARATION);

  const panelInfo = extractPanelInfo(opGraph, opts);
  lines.push(`<PROGRAM name="${escapeXmlAttr(panelInfo.name)}">`);

  // ADR-065 Q3: NFP safety marking — always emitted, even without comments
  for (const nfpLine of getNfpHeaderLines()) {
    lines.push(`${INDENT}<!-- ${nfpLine} -->`);
  }

  if (opts.includeComments !== false) {
    lines.push(`${INDENT}<!-- Generated by Monolith CNC Export -->`);
    lines.push(`${INDENT}<!-- Program: ${escapeXmlContent(opts.programName)} -->`);
    lines.push(`${INDENT}<!-- Date: ${formatTimestamp()} -->`);
    if (opGraph.metadata?.jobId) {
      lines.push(`${INDENT}<!-- Job: ${escapeXmlContent(opGraph.metadata.jobId)} -->`);
    }
  }

  lines.push(`${INDENT}<HEADER>`);
  lines.push(
    `${INDENT}${INDENT}<DIM X="${formatCixNumber(panelInfo.width)}" Y="${formatCixNumber(panelInfo.height)}" Z="${formatCixNumber(panelInfo.thickness)}"/>`
  );
  lines.push(`${INDENT}</HEADER>`);

  if (!opGraph.operations || opGraph.operations.length === 0) {
    lines.push(`${INDENT}<MACHINING/>`);
    lines.push('</PROGRAM>');
    warnings.push('No operations to process');

    return {
      status: 'OK',
      gcode: lines.join('\n'),
      warnings,
      stats: {
        lineCount: lines.length,
        toolChanges: 0,
        operationCount: 0,
        estimatedTimeSeconds: 0,
      },
    };
  }

  const normalizedOps = normalizeOperations(opGraph.operations, {
    preserveOrder: opts.preserveOrder ?? false,
    groupByTool: true,
    optimizePath: false,
  });

  const toolMap = buildToolMap(machine);

  lines.push(`${INDENT}<MACHINING>`);

  let operationCount = 0;
  let toolChanges = 0;
  let estimatedTime = 0;
  let currentToolId: string | null = null;

  for (const op of normalizedOps) {
    if (op.toolId !== currentToolId) {
      if (currentToolId !== null) toolChanges++;
      currentToolId = op.toolId;
    }

    const result = buildOperationElement(op, toolMap, opts, warnings);
    if (result) {
      lines.push(result.xml);
      estimatedTime += result.estimatedTime;
      operationCount++;
    }
  }

  lines.push(`${INDENT}</MACHINING>`);
  lines.push('</PROGRAM>');

  const output = lines.join('\n');

  const stats: PostProcessStats = {
    lineCount: lines.length,
    toolChanges,
    operationCount,
    estimatedTimeSeconds: Math.round(estimatedTime),
  };

  return {
    status: 'OK',
    gcode: output,
    warnings,
    stats,
  };
}

// ============================================================================
// Panel Info
// ============================================================================

interface PanelInfo {
  name: string;
  width: number;
  height: number;
  thickness: number;
}

function extractPanelInfo(
  opGraph: OperationGraph,
  opts: PostProcessOptions
): PanelInfo {
  const name = opts.programName || 'PANEL';

  let maxX = 0;
  let maxY = 0;
  let maxDepth = 0;

  for (const op of opGraph.operations ?? []) {
    maxX = Math.max(maxX, op.position.x);
    maxY = Math.max(maxY, op.position.y);

    if (op.type === 'DRILL' || op.type === 'BORE') {
      const depthOp = op as DrillOperation | BoreOperation;
      maxDepth = Math.max(maxDepth, depthOp.depth);
    }
  }

  return {
    name,
    width: maxX > 0 ? Math.ceil(maxX + 50) : 600,
    height: maxY > 0 ? Math.ceil(maxY + 50) : 720,
    thickness: maxDepth > 0 ? Math.ceil(maxDepth + 2) : DEFAULT_THICKNESS,
  };
}

// ============================================================================
// Operation Element Builders
// ============================================================================

function buildOperationElement(
  op: Operation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { xml: string; estimatedTime: number } | null {
  switch (op.type) {
    case 'DRILL':
      return buildDrillElement(op as DrillOperation, toolMap, opts, warnings);
    case 'BORE':
      return buildBoreElement(op as BoreOperation, toolMap, opts, warnings);
    default:
      warnings.push(
        `Unsupported operation type for CIX: ${op.type} (operation ${op.id})`
      );
      return null;
  }
}

function buildDrillElement(
  op: DrillOperation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { xml: string; estimatedTime: number } {
  const toolInfo = toolMap[op.toolId];
  if (!toolInfo) {
    warnings.push(`CIX: Unknown tool '${op.toolId}', defaulting to TNO=1`);
  }
  const toolNumber = toolInfo?.toolNumber ?? 1;
  const diameter = op.diameter ?? toolInfo?.diameter ?? 5;

  const attrs: string[] = [
    `X="${formatCixNumber(op.position.x)}"`,
    `Y="${formatCixNumber(op.position.y)}"`,
    `Z="${formatCixNumber(-op.depth)}"`,
    `DIA="${formatCixNumber(diameter)}"`,
    `THROUGH="${op.throughHole ? 'yes' : 'no'}"`,
    `TNO="${toolNumber}"`,
    `ID="${escapeXmlAttr(op.id)}"`,
  ];

  if (opts.includeComments !== false && op.comment) {
    attrs.push(`COMMENT="${escapeXmlAttr(op.comment)}"`);
  }

  const xml = `${INDENT}${INDENT}<BORE ${attrs.join(' ')}/>`;

  const feedRate = op.feedRate ?? toolInfo?.diameter
    ? (toolInfo?.diameter ?? 8) < 8 ? 2500 : 2200
    : 2200;
  const estimatedTime = 0.5 + (op.depth / feedRate) * 60 + 0.3;

  return { xml, estimatedTime };
}

function buildBoreElement(
  op: BoreOperation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { xml: string; estimatedTime: number } {
  const toolInfo = toolMap[op.toolId];
  if (!toolInfo) {
    warnings.push(`CIX: Unknown tool '${op.toolId}', defaulting to TNO=1`);
  }
  const toolNumber = toolInfo?.toolNumber ?? 1;

  const attrs: string[] = [
    `X="${formatCixNumber(op.position.x)}"`,
    `Y="${formatCixNumber(op.position.y)}"`,
    `Z="${formatCixNumber(-op.depth)}"`,
    `DIA="${formatCixNumber(op.diameter)}"`,
    `THROUGH="no"`,
    `TNO="${toolNumber}"`,
    `ID="${escapeXmlAttr(op.id)}"`,
  ];

  if (opts.includeComments !== false && op.comment) {
    attrs.push(`COMMENT="${escapeXmlAttr(op.comment)}"`);
  }

  const xml = `${INDENT}${INDENT}<BORE ${attrs.join(' ')}/>`;

  const feedRate = op.feedRate ?? 1200;
  const estimatedTime = 0.5 + (op.depth / feedRate) * 120 + 0.3;

  return { xml, estimatedTime };
}

// ============================================================================
// Tool Map Builder
// ============================================================================

function buildToolMap(machine: MachineProfile): ToolMap {
  const toolMap: ToolMap = {};

  for (let i = 0; i < machine.tools.length; i++) {
    const tool = machine.tools[i];
    toolMap[tool.toolId] = {
      toolNumber: i + 1,
      diameter: tool.diameter,
      description: `${tool.type} D${tool.diameter}`,
    };
  }

  return toolMap;
}

// ============================================================================
// XML Formatting Utilities
// ============================================================================

export function formatCixNumber(value: number, decimals = 3): string {
  const multiplier = Math.pow(10, decimals);
  const rounded = Math.round(value * multiplier) / multiplier;

  if (Number.isInteger(rounded)) {
    return rounded.toString();
  }

  const fixed = rounded.toFixed(decimals);
  return fixed.replace(/0+$/, '').replace(/\.$/, '');
}

export function escapeXmlAttr(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
    .substring(0, 80);
}

export function escapeXmlContent(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .substring(0, 80);
}

// ============================================================================
// Export
// ============================================================================

export default cixPostProcessor;
