/**
 * xxl.ts - SCM/Morbidelli XXL (Xilog) Format Post Processor
 *
 * Generates SCM-compatible XXL files for Morbidelli and other SCM Group
 * CNC machining centers. XXL is a text-based format used by Xilog Plus
 * CAM software to program SCM machines.
 *
 * ## XXL Format Overview
 *
 * ```
 * XILOG
 * NAME=panel_001
 * DIM_X=600
 * DIM_Y=720
 * DIM_Z=18
 * ; Comment
 * OPERATION BOR
 *   X=50 Y=37 DEPTH=12.5 DIA=8 TNO=1
 * END_OPERATION
 * END
 * ```
 *
 * ## Supported Operations
 * - BOR: Vertical drilling / boring (DRILL + BORE operation types)
 * - Unsupported types emit warnings (PKT, ROUT, SLOT reserved for future)
 *
 * @see https://wooddesigner.org/help-centre/polyboard-cnc-integration/
 * @version 1.0.0 - Phase T028-P4: XXL post-processor
 */

import type { MachineProfile } from '../../machine/machineProfile';
import type {
  OperationGraph,
  Operation,
  DrillOperation,
  BoreOperation,
} from '../../operation/operationTypes';
import type {
  PostProcessor,
  PostProcessOptions,
  PostProcessResult,
  PostProcessStats,
  ToolMap,
} from '../types';
import { normalizeOperations } from '../normalizeOperations';
import { formatTimestamp } from '../emit/format';

// ============================================================================
// Constants
// ============================================================================

/** XXL file header keyword */
const XXL_HEADER = 'XILOG';

/** Default panel thickness when not specified (mm) */
const DEFAULT_THICKNESS = 18;

// ============================================================================
// XXL Post Processor
// ============================================================================

/**
 * XXL dialect post processor.
 * Generates SCM-compatible XXL (Xilog) files.
 */
export const xxlPostProcessor: PostProcessor = {
  dialect: 'XXL',
  fileExt: '.xxl',

  post(
    opGraph: OperationGraph,
    machine: MachineProfile,
    opts: PostProcessOptions
  ): PostProcessResult {
    try {
      return generateXxl(opGraph, machine, opts);
    } catch (error) {
      return {
        status: 'FAIL',
        errors: [
          `XXL post-processor error: ${error instanceof Error ? error.message : String(error)}`,
        ],
      };
    }
  },
};

// ============================================================================
// Main Generation Function
// ============================================================================

function generateXxl(
  opGraph: OperationGraph,
  machine: MachineProfile,
  opts: PostProcessOptions
): PostProcessResult {
  const warnings: string[] = [];
  const lines: string[] = [];

  // XXL header
  lines.push(XXL_HEADER);

  // Program name
  const programName = sanitizeXxlString(opts.programName || 'PANEL');
  lines.push(`NAME=${programName}`);

  // Extract panel dimensions
  const panelInfo = extractPanelInfo(opGraph, opts);
  lines.push(`DIM_X=${formatXxlNumber(panelInfo.width)}`);
  lines.push(`DIM_Y=${formatXxlNumber(panelInfo.height)}`);
  lines.push(`DIM_Z=${formatXxlNumber(panelInfo.thickness)}`);

  // Comment with generation info
  if (opts.includeComments !== false) {
    lines.push('; Generated by Monolith CNC Export');
    lines.push(`; Program: ${sanitizeXxlString(opts.programName)}`);
    lines.push(`; Date: ${formatTimestamp()}`);
    if (opGraph.metadata?.jobId) {
      lines.push(`; Job: ${sanitizeXxlString(opGraph.metadata.jobId)}`);
    }
  }

  // Handle empty operations
  if (!opGraph.operations || opGraph.operations.length === 0) {
    lines.push('; No operations');
    lines.push('END');
    warnings.push('No operations to process');

    return {
      status: 'OK',
      gcode: lines.join('\n'),
      warnings,
      stats: {
        lineCount: lines.length,
        toolChanges: 0,
        operationCount: 0,
        estimatedTimeSeconds: 0,
      },
    };
  }

  // Normalize operations
  const normalizedOps = normalizeOperations(opGraph.operations, {
    preserveOrder: opts.preserveOrder ?? false,
    groupByTool: true,
    optimizePath: false,
  });

  // Build tool map
  const toolMap = buildToolMap(machine);

  // Operation blocks
  let operationCount = 0;
  let toolChanges = 0;
  let estimatedTime = 0;
  let currentToolId: string | null = null;

  for (const op of normalizedOps) {
    // Track tool changes
    if (op.toolId !== currentToolId) {
      if (currentToolId !== null) toolChanges++;
      currentToolId = op.toolId;
    }

    const result = buildOperationBlock(op, toolMap, opts, warnings);
    if (result) {
      lines.push(result.block);
      estimatedTime += result.estimatedTime;
      operationCount++;
    }
  }

  // End marker
  lines.push('END');

  const output = lines.join('\n');

  const stats: PostProcessStats = {
    lineCount: lines.length,
    toolChanges,
    operationCount,
    estimatedTimeSeconds: Math.round(estimatedTime),
  };

  return {
    status: 'OK',
    gcode: output,
    warnings,
    stats,
  };
}

// ============================================================================
// Panel Info
// ============================================================================

interface PanelInfo {
  name: string;
  width: number;
  height: number;
  thickness: number;
}

function extractPanelInfo(
  opGraph: OperationGraph,
  opts: PostProcessOptions
): PanelInfo {
  const name = opts.programName || 'PANEL';

  let maxX = 0;
  let maxY = 0;
  let maxDepth = 0;

  for (const op of opGraph.operations ?? []) {
    maxX = Math.max(maxX, op.position.x);
    maxY = Math.max(maxY, op.position.y);

    if (op.type === 'DRILL' || op.type === 'BORE') {
      const depthOp = op as DrillOperation | BoreOperation;
      maxDepth = Math.max(maxDepth, depthOp.depth);
    }
  }

  return {
    name,
    width: maxX > 0 ? Math.ceil(maxX + 50) : 600,
    height: maxY > 0 ? Math.ceil(maxY + 50) : 720,
    thickness: maxDepth > 0 ? Math.ceil(maxDepth + 2) : DEFAULT_THICKNESS,
  };
}

// ============================================================================
// Operation Block Builders
// ============================================================================

function buildOperationBlock(
  op: Operation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { block: string; estimatedTime: number } | null {
  switch (op.type) {
    case 'DRILL':
      return buildDrillBlock(op as DrillOperation, toolMap, opts, warnings);
    case 'BORE':
      return buildBoreBlock(op as BoreOperation, toolMap, opts, warnings);
    default:
      warnings.push(
        `Unsupported operation type for XXL: ${op.type} (operation ${op.id})`
      );
      return null;
  }
}

function buildDrillBlock(
  op: DrillOperation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { block: string; estimatedTime: number } {
  const toolInfo = toolMap[op.toolId];
  if (!toolInfo) {
    warnings.push(`XXL: Unknown tool '${op.toolId}', defaulting to TNO=1`);
  }
  const toolNumber = toolInfo?.toolNumber ?? 1;
  const diameter = op.diameter ?? toolInfo?.diameter ?? 5;

  const params: string[] = [
    `X=${formatXxlNumber(op.position.x)}`,
    `Y=${formatXxlNumber(op.position.y)}`,
    `DEPTH=${formatXxlNumber(op.depth)}`,
    `DIA=${formatXxlNumber(diameter)}`,
    `TNO=${toolNumber}`,
    `THROUGH=${op.throughHole ? 1 : 0}`,
    `ID=${sanitizeXxlString(op.id)}`,
  ];

  const lines: string[] = ['OPERATION BOR'];
  lines.push(`  ${params.join(' ')}`);

  if (opts.includeComments !== false && op.comment) {
    lines.push(`  ; ${sanitizeXxlString(op.comment)}`);
  }

  lines.push('END_OPERATION');
  const block = lines.join('\n');

  const feedRate = op.feedRate ?? toolInfo?.diameter
    ? (toolInfo?.diameter ?? 8) < 8 ? 2500 : 2200
    : 2200;
  const estimatedTime = 0.5 + (op.depth / feedRate) * 60 + 0.3;

  return { block, estimatedTime };
}

function buildBoreBlock(
  op: BoreOperation,
  toolMap: ToolMap,
  opts: PostProcessOptions,
  warnings: string[]
): { block: string; estimatedTime: number } {
  const toolInfo = toolMap[op.toolId];
  if (!toolInfo) {
    warnings.push(`XXL: Unknown tool '${op.toolId}', defaulting to TNO=1`);
  }
  const toolNumber = toolInfo?.toolNumber ?? 1;

  const params: string[] = [
    `X=${formatXxlNumber(op.position.x)}`,
    `Y=${formatXxlNumber(op.position.y)}`,
    `DEPTH=${formatXxlNumber(op.depth)}`,
    `DIA=${formatXxlNumber(op.diameter)}`,
    `TNO=${toolNumber}`,
    `THROUGH=0`,
    `ID=${sanitizeXxlString(op.id)}`,
  ];

  const lines: string[] = ['OPERATION BOR'];
  lines.push(`  ${params.join(' ')}`);

  if (opts.includeComments !== false && op.comment) {
    lines.push(`  ; ${sanitizeXxlString(op.comment)}`);
  }

  lines.push('END_OPERATION');
  const block = lines.join('\n');

  const feedRate = op.feedRate ?? 1200;
  const estimatedTime = 0.5 + (op.depth / feedRate) * 120 + 0.3;

  return { block, estimatedTime };
}

// ============================================================================
// Tool Map Builder
// ============================================================================

function buildToolMap(machine: MachineProfile): ToolMap {
  const toolMap: ToolMap = {};

  for (let i = 0; i < machine.tools.length; i++) {
    const tool = machine.tools[i];
    toolMap[tool.toolId] = {
      toolNumber: i + 1,
      diameter: tool.diameter,
      description: `${tool.type} D${tool.diameter}`,
    };
  }

  return toolMap;
}

// ============================================================================
// Formatting Utilities
// ============================================================================

export function formatXxlNumber(value: number, decimals = 3): string {
  const multiplier = Math.pow(10, decimals);
  const rounded = Math.round(value * multiplier) / multiplier;

  if (Number.isInteger(rounded)) {
    return rounded.toString();
  }

  const fixed = rounded.toFixed(decimals);
  return fixed.replace(/0+$/, '').replace(/\.$/, '');
}

export function sanitizeXxlString(text: string): string {
  return text
    .replace(/[\r\n]/g, ' ')
    .replace(/[=;]/g, '_')
    .substring(0, 80);
}

// ============================================================================
// Export
// ============================================================================

export default xxlPostProcessor;
